# Generated by Django 5.0.4 on 2024-04-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_about_aboutimage_carousel_gallery_home_homegallery_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facebook',
        ),
        migrations.DeleteModel(
            name='Instagram',
        ),
        migrations.DeleteModel(
            name='Linkedin',
        ),
    ]
