# Generated by Django 5.0.4 on 2024-04-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_facebook_delete_instagram_delete_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='HomeAbout/')),
            ],
        ),
        migrations.CreateModel(
            name='HomeFoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='HomeFoods/')),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='AboutImage',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='carousel',
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.DeleteModel(
            name='Homemenuimages',
        ),
        migrations.DeleteModel(
            name='Homemenus',
        ),
        migrations.DeleteModel(
            name='Homeservices',
        ),
        migrations.DeleteModel(
            name='Homevideo',
        ),
        migrations.DeleteModel(
            name='Mailid',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuItems',
        ),
        migrations.DeleteModel(
            name='mobile',
        ),
        migrations.DeleteModel(
            name='OurTeam',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='Testimonials',
        ),
        migrations.DeleteModel(
            name='whatwedos',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='Description',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='homegallery',
            name='AlternativeImage',
        ),
        migrations.AddField(
            model_name='homegallery',
            name='AlternateImage',
            field=models.ImageField(default=1, upload_to='HomeGallery/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='Image',
            field=models.ImageField(upload_to='Gallery/'),
        ),
        migrations.AlterField(
            model_name='homegallery',
            name='Image',
            field=models.ImageField(upload_to='HomeGallery/'),
        ),
        migrations.AlterField(
            model_name='homeimage',
            name='Image',
            field=models.ImageField(upload_to='HomeImage/'),
        ),
    ]
